"""empty message

Revision ID: 85f23b2cbd84
Revises: d320f56bce76
Create Date: 2022-02-23 11:38:41.809870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f23b2cbd84'
down_revision = 'd320f56bce76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_addr', sa.String(length=20), nullable=True),
    sa.Column('user', sa.String(length=20), nullable=True),
    sa.Column('first_access_at', sa.DateTime(), nullable=True),
    sa.Column('last_access_at', sa.DateTime(), nullable=True),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('0', '1', '2'), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_record_first_access_at'), 'access_record', ['first_access_at'], unique=False)
    op.create_index(op.f('ix_access_record_last_access_at'), 'access_record', ['last_access_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_record_last_access_at'), table_name='access_record')
    op.drop_index(op.f('ix_access_record_first_access_at'), table_name='access_record')
    op.drop_table('access_record')
    # ### end Alembic commands ###
