"""empty message

Revision ID: d320f56bce76
Revises: 
Create Date: 2022-02-23 11:13:15.023885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd320f56bce76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_ip',
    sa.Column('ip', mysql.VARCHAR(length=255), nullable=True, comment='ip'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_access_time', mysql.DATETIME(), nullable=True),
    sa.Column('today_times', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='今天的访问次数'),
    sa.Column('first_access_time', mysql.DATETIME(), nullable=True, comment='第一次访问时间'),
    sa.Column('user', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
